sudo: required

services:
- docker

script:
- docker pull gcr.io/kubernetes-helm/tiller:v2.12.0
- docker tag gcr.io/kubernetes-helm/tiller:v2.12.0 alanpeng/tiller:v2.12.0

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push alanpeng/tiller:v2.12.0
  on:
    all_branches: true
