sudo: required

services:
- docker

script:
- docker pull gcr.io/heptio-images/contour:master
- docker tag gcr.io/heptio-images/contour:master alanpeng/contour:master

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push alanpeng/contour:master
  on:
    all_branches: true
